import re

with open("app/src/main/java/com/example/ui/strings/StringsRo.kt", "w") as f:
    f.write("""package com.example.ui.strings

object StringsRo : AppStrings {
    override val dpadUp = "Sus"
    override val dpadDown = "Jos"
    override val dpadLeft = "Stânga"
    override val dpadRight = "Dreapta"
    override val appTitle = "ROMÂNIA 2048"
    override val appSubtitle = "Construiește România, piesă cu piesă!"
    override val playNow = "JOACĂ ACUM"
    override val record = "Record"
    override val currentLevelTitle = "NIVEL ACTUAL"
    override val levelPrefix = "Nivel "
    override val collectionTitle = "COLECȚIE"
    override val btnLevels = "NIVELURI"
    override val btnAchievements = "REALIZĂRI"
    override val btnSettings = "SETĂRI"
    override val btnAbout = "DESPRE JOC"
    override val removeAdsTitle = "Joacă fără reclame"
    override val adsRemovedMsg = "Reclamele interstițiale sunt dezactivate"
    override val removeAdsDesc = "Elimină reclamele interstițiale și bucură-te de o experiență de joc mai plăcută."
    override val removeAdsBtn = "ELIMINĂ RECLAMELE — 6,99 lei"
    override val removeAdsDisclaimer = "Achiziție unică. Reclamele recompensate pentru Undo și Continuă după Game Over rămân disponibile."
    override val restorePurchaseBtn = "RESTAUREAZĂ ACHIZIȚIA"
    override val languageSelector = "Limba: RO"

    override val modeSelectionTitle = "🎮 ALEGE MODUL DE JOC"
    override val modeSelectionDesc = "Selectează experiența de joc pe care o dorești:"
    override val modeAdventureTitle = "MOD AVENTURĂ"
    override val modeAdventureDesc = "Progres pe niveluri"
    override val modeAdventureLongDesc = "Descoperă preparatele românești, completează colecția și deblochează noi niveluri pas cu pas."
    override val unlockedLevelsPrefix = "Niveluri deblocate: "
    override val viewLevelsBtn = "VEZI NIVELURILE"
    override val modeInfiniteTitle = "MOD INFINIT"
    override val modeInfiniteDesc = "Clasic fără sfârșit"
    override val modeInfiniteLongDesc = "Joacă fără limită, combină cât mai multe piese și încearcă să-ți depășești recordul personal."

    override val levelsTitle = "🗺 NIVELURI"
    override val levelsSubtitle = "Progresează prin nivelurile României combinând piese și atingând obiectivele stabilite!"
    override val levelObjectivePrefix = "Obiectiv: Descoperă Piesa "
    override val levelRewardPrefix = "Recompensă: "
    override val levelBtnPlay = "JOACĂ"
    override val levelBtnReplay = "REJOACĂ"

    override val collectionHeaderTitle = "🎨 COLECȚIE"
    override val collectionSubtitle = "Toate piesele românești pe care le-ai creat în joc "
    override val statusUnlocked = "DEBLOCAT"
    override val statusLocked = "BLOCAT"
    override fun collectionLockedDesc(value: Int) = "Atinge piesa $value în joc pentru a debloca acest obiect tradițional!"

    override val achievementsTitle = "🏆 REALIZĂRI"
    override fun achievementsSubtitle(count: Int) = "Deblochează toate cele $count de realizări "

    override val aboutTitle = "ℹ DESPRE JOC"
    override val aboutDescription = "„ROMÂNIA 2048 este un joc casual inspirat de România, de lucrurile mici și mari care ne definesc și de plăcerea de a construi ceva pas cu pas.”"
    override val version = "Versiunea 1.0.0"
    override val copyright = "© România 2048"

    override val settingsTitle = "⚙ SETĂRI"
    override val audioSection = "AUDIO & VIBRAȚII"
    override val visualSection = "🌙 TEMĂ VIZUALĂ"
    override val gamePrefsSection = "⚡ PREFERINȚE JOC"
    override val resetSection = "🗑️ RESETARE PROGRES"
    override val musicVol = "🎵 VOLUM MUZICĂ: "
    override val sfxVol = "🔊 VOLUM EFECTE SONORE: "
    override val vibration = "🔔 VIBRAȚII"
    override val themeLight = "LIGHT"
    override val themeDark = "DARK"
    override val themeSystem = "SYSTEM"
    override val romanianTheme = "🎨 TEMĂ ROMÂNEASCĂ"
    override val animations = "⚡ ANIMAȚII"
    override val confirmRestartPref = "CONFIRMĂ RESTART"

    override val achievementUnlocked = "🏆 REALIZARE DEBLOCATĂ!"

    override val btnCancel = "ANULEAZĂ"
    override val restartDialogTitle = "🔄 Joc Nou"
    override val restartDialogDesc = "Ești sigur că vrei să începi un joc nou? Progresul jocului curent va fi resetat."
    override val restartDialogConfirm = "DA, RESTART"
    override val pauseDialogTitle = "⏸ JOC PUS PE PAUZĂ"
    override val victoryTitle = "FELICITĂRI!"
    override val victoryDesc = "„Ai construit România, piesă cu piesă!”"
    override val btnContinuePlaying = "▶ CONTINUĂ"
    override val btnPlayAgain = "🔄 JOACĂ DIN NOU"
    override val btnHome = "🏠 MENIU PRINCIPAL"
    override val gameOverTitle = "GAME OVER"
    override val gameOverDesc = "Nu mai ai mutări disponibile."
    override val gameOverNewRecord = "🏆 RECORD NOU! "
    override fun gameOverScore(score: Int, highScore: Int) = "Scor final: $score\\nRecord: $highScore"
    override val continueGameBtn = "▶ CONTINUĂ JOCUL"
    override val continueAdBtn = "🎬 CONTINUĂ (RECLAMĂ)"
    override val extraUndoTitle = "↩ Undo Suplimentar"
    override val extraUndoBtnFree = "▶ PRIMEȘTE UNDO"
    override val extraUndoBtnAd = "🎬 VEZI RECLAMĂ (+1 UNDO)"
    override val extraUndoDescAd = "Folosește o șansă pentru a-ți corecta ultima mutare urmărind o scurtă reclamă."
    override val extraUndoDescFree = "Folosește o șansă pentru a-ți corecta ultima mutare gratuit."
    override val levelCompleteTitle = "NIVEL COMPLETAT!"
    override val rewardUnlocked = "🎁 Recompensă deblocată:"
    override val resetProgressTitle = "⚠️ Resetare Progres"
    override val resetProgressDesc = "Ești absolut sigur că vrei să ștergi TOT progresul, nivelurile și realizările? Această acțiune nu poate fi anulată!"
    override val resetProgressConfirm = "DA, RESETEAZĂ TOT"

    override fun getLevelName(level: Int) = "NIVEL $level"
    override val infiniteModeTop = "♾️ MOD INFINIT"
    override val score = "SCOR"
    override val recordUpper = "RECORD"
    override val restartBtn = "RESTART"
    override val undoBtn = "UNDO"
    override fun objectiveAdventure(level: Int, emoji: String, name: String, val_: Int) = "🎯 OBIECTIV NIVEL $level: Descoperă $emoji $name ($val_)"
    override val objectiveInfinite = "🎯 OBIECTIV: Ajunge la piesa 2048!"
    override fun objectiveAdventureDesc(name: String) = "„Combină două piese identice pentru a descoperi $name!”"
    override val objectiveInfiniteDesc = "„Combină două piese identice pentru a construi România, piesă cu piesă!”"
    override val gamePaused = "JOC ÎN PAUZĂ"
    override val resumeGameBtn = "CONTINUĂ JOCUL"

    override val fallbackName = "Mister "
    override val fallbackDesc = "O piesă necunoscută, apărută din neant."
    override val fallbackBadge = "???"

    override val gameLevel1Name = "Începutul"
    override val gameLevel1Reward = "Covrig (8)"
    override val gameLevel2Name = "Gustarea"
    override val gameLevel2Reward = "Plăcintă (16)"
    override val gameLevel3Name = "Felul Întâi"
    override val gameLevel3Reward = "Ciorbă (32)"
    override val gameLevel4Name = "La Stână"
    override val gameLevel4Reward = "Mămăligă & Brânză (64)"
    override val gameLevel5Name = "Grătarul"
    override val gameLevel5Reward = "Mici (128)"
    override val gameLevel6Name = "Masa de Duminică"
    override val gameLevel6Reward = "Sarmale (256)"
    override val gameLevel7Name = "Tradiția"
    override val gameLevel7Reward = "Cozonac (512)"
    override val gameLevel8Name = "Moștenirea"
    override val gameLevel8Reward = "Castelul Bran (1024)"
    override val gameLevel9Name = "Simbolul"
    override val gameLevel9Reward = "Ateneul (2048)"
    override val gameLevel10Name = "Eroii"
    override val gameLevel10Reward = "Mihai Viteazul (4096)"
    override val gameLevel11Name = "Legenda"
    override val gameLevel11Reward = "Lupul Dacic (8192)"
    override val gameLevel12Name = "Absolutul"
    override val gameLevel12Reward = "Coroana Regală (16384)"

    override val reg2name = "Covrig"
    override val reg2desc = "Covrigul – combustibilul oficial al românului grăbit."
    override val reg2badge = "Gustare"
    override val reg4name = "Plăcintă"
    override val reg4desc = "Fie că e cu brânză, mere sau dovleac, e mereu caldă și bună."
    override val reg4badge = "Desert"
    override val reg8name = "Ciorbă de Burtă"
    override val reg8desc = "Remediul suprem pentru orice dimineață grea."
    override val reg8badge = "Felul 1"
    override val reg16name = "Mămăligă cu Brânză"
    override val reg16desc = "Simplă, autentică, de neînlocuit la stână."
    override val reg16badge = "Tradiție"
    override val reg32name = "Mici cu Muștar"
    override val reg32desc = "Regii neîncoronați ai oricărui grătar de 1 Mai."
    override val reg32badge = "Grătar"
    override val reg64name = "Sarmale"
    override val reg64desc = "Făcute cu drag de bunica. Mereu mai bune a doua zi."
    override val reg64badge = "Festin"
    override val reg128name = "Cozonac"
    override val reg128desc = "Aroma Crăciunului și a Paștelui în fiecare casă."
    override val reg128badge = "Sărbătoare"
    override val reg256name = "Cafea la Ibric"
    override val reg256desc = "Cum se începeau diminețile înainte de espressoare."
    override val reg256badge = "Energie"
    override val reg512name = "Castelul Bran"
    override val reg512desc = "Legenda lui Dracula, vizitată de o lume întreagă."
    override val reg512badge = "Monument"
    override val reg1024name = "Ateneul Român"
    override val reg1024desc = "Simbolul culturii și eleganței din inima Bucureștiului."
    override val reg1024badge = "Cultură"
    override val reg2048name = "România 2048"
    override val reg2048desc = "Ai atins scopul suprem al jocului! Felicitări!"
    override val reg2048badge = "Victorie"
    override val reg4096name = "Mihai Viteazul"
    override val reg4096desc = "Simbol al curajului și al unirii tuturor românilor."
    override val reg4096badge = "Istorie"
    override val reg8192name = "Lupul Dacic"
    override val reg8192desc = "Stindardul strămoșilor noștri, stârnind frica în inamici."
    override val reg8192badge = "Mitologie"
    override val reg16384name = "Coroana Regală"
    override val reg16384desc = "Coroana de oțel, forjată din tunurile de la Plevna."
    override val reg16384badge = "Regalitate"

    override fun getAchievementTitle(id: String) = when(id) {
        "1" -> "Prima Gustare"
        "2" -> "Ceva Dulce"
        "3" -> "La Ciorbă"
        "4" -> "Autentic Românesc"
        "5" -> "Grataragiu"
        "6" -> "Masa în Familie"
        "7" -> "Miros de Sărbătoare"
        "8" -> "Pauza de Cafea"
        "9" -> "Turist în Transilvania"
        "10" -> "Om de Cultură"
        "11" -> "Patriot Adevărat"
        "12" -> "Erou Național"
        "13" -> "Spirit Dacic"
        "14" -> "Sânge Albastru"
        "15" -> "Jucător Constant"
        "16" -> "Maestru 2048"
        "17" -> "Începător"
        "18" -> "Amator"
        "19" -> "Profesionist"
        "20" -> "Călător"
        else -> "Necunoscut"
    }
    
    override fun getAchievementDesc(id: String) = when(id) {
        "1" -> "Descoperă piesa 4 (Plăcintă)"
        "2" -> "Descoperă piesa 8 (Ciorbă)"
        "3" -> "Descoperă piesa 16 (Mămăligă)"
        "4" -> "Descoperă piesa 32 (Mici)"
        "5" -> "Descoperă piesa 64 (Sarmale)"
        "6" -> "Descoperă piesa 128 (Cozonac)"
        "7" -> "Descoperă piesa 256 (Cafea)"
        "8" -> "Descoperă piesa 512 (Castel)"
        "9" -> "Descoperă piesa 1024 (Ateneu)"
        "10" -> "Descoperă piesa 2048 (România)"
        "11" -> "Descoperă piesa 4096 (Mihai Viteazul)"
        "12" -> "Descoperă piesa 8192 (Lupul Dacic)"
        "13" -> "Descoperă piesa 16384 (Coroana Regală)"
        "14" -> "Obține cea mai rară piesă posibilă!"
        "15" -> "Completează 3 niveluri în Modul Aventură"
        "16" -> "Completează 10 niveluri în Modul Aventură"
        "17" -> "Atinge un scor de 10.000 pct"
        "18" -> "Atinge un scor de 25.000 pct"
        "19" -> "Atinge un scor de 50.000 pct"
        "20" -> "Joacă 5 jocuri în Modul Infinit"
        else -> "Necunoscut"
    }
}
""")

with open("app/src/main/java/com/example/ui/strings/StringsEn.kt", "w") as f:
    f.write("""package com.example.ui.strings

object StringsEn : AppStrings {
    override val dpadUp = "Up"
    override val dpadDown = "Down"
    override val dpadLeft = "Left"
    override val dpadRight = "Right"
    override val appTitle = "ROMANIA 2048"
    override val appSubtitle = "Build Romania, tile by tile!"
    override val playNow = "PLAY NOW"
    override val record = "Record"
    override val currentLevelTitle = "CURRENT LEVEL"
    override val levelPrefix = "Level "
    override val collectionTitle = "COLLECTION"
    override val btnLevels = "LEVELS"
    override val btnAchievements = "ACHIEVEMENTS"
    override val btnSettings = "SETTINGS"
    override val btnAbout = "ABOUT"
    override val removeAdsTitle = "Play Ad-Free"
    override val adsRemovedMsg = "Interstitial ads are disabled"
    override val removeAdsDesc = "Remove interstitial ads and enjoy a smoother gaming experience."
    override val removeAdsBtn = "REMOVE ADS — 6.99 RON"
    override val removeAdsDisclaimer = "One-time purchase. Rewarded ads for Undo and Continue after Game Over will still be available."
    override val restorePurchaseBtn = "RESTORE PURCHASE"
    override val languageSelector = "Language: EN"

    override val modeSelectionTitle = "🎮 CHOOSE GAME MODE"
    override val modeSelectionDesc = "Select the gaming experience you want:"
    override val modeAdventureTitle = "ADVENTURE MODE"
    override val modeAdventureDesc = "Level-based progression"
    override val modeAdventureLongDesc = "Discover Romanian foods, complete your collection and unlock new levels step by step."
    override val unlockedLevelsPrefix = "Unlocked levels: "
    override val viewLevelsBtn = "VIEW LEVELS"
    override val modeInfiniteTitle = "INFINITE MODE"
    override val modeInfiniteDesc = "Endless classic"
    override val modeInfiniteLongDesc = "Play without limits, merge as many tiles as you can and try to beat your personal high score."

    override val levelsTitle = "🗺 LEVELS"
    override val levelsSubtitle = "Progress through Romania's levels by merging tiles and reaching the set objectives!"
    override val levelObjectivePrefix = "Objective: Discover Tile "
    override val levelRewardPrefix = "Reward: "
    override val levelBtnPlay = "PLAY"
    override val levelBtnReplay = "REPLAY"

    override val collectionHeaderTitle = "🎨 COLLECTION"
    override val collectionSubtitle = "All the Romanian tiles you have created in the game "
    override val statusUnlocked = "UNLOCKED"
    override val statusLocked = "LOCKED"
    override fun collectionLockedDesc(value: Int) = "Reach tile $value in the game to unlock this traditional item!"

    override val achievementsTitle = "🏆 ACHIEVEMENTS"
    override fun achievementsSubtitle(count: Int) = "Unlock all $count achievements "

    override val aboutTitle = "ℹ ABOUT THE GAME"
    override val aboutDescription = "\\"ROMANIA 2048 is a casual game inspired by Romania, the big and small things that define us, and the joy of building something step by step.\\""
    override val version = "Version 1.0.0"
    override val copyright = "© Romania 2048"

    override val settingsTitle = "⚙ SETTINGS"
    override val audioSection = "AUDIO & VIBRATION"
    override val visualSection = "🌙 VISUAL THEME"
    override val gamePrefsSection = "⚡ GAME PREFERENCES"
    override val resetSection = "🗑️ RESET PROGRESS"
    override val musicVol = "🎵 MUSIC VOLUME: "
    override val sfxVol = "🔊 SFX VOLUME: "
    override val vibration = "🔔 VIBRATION"
    override val themeLight = "LIGHT"
    override val themeDark = "DARK"
    override val themeSystem = "SYSTEM"
    override val romanianTheme = "🎨 ROMANIAN THEME"
    override val animations = "⚡ ANIMATIONS"
    override val confirmRestartPref = "CONFIRM RESTART"

    override val achievementUnlocked = "🏆 ACHIEVEMENT UNLOCKED!"

    override val btnCancel = "CANCEL"
    override val restartDialogTitle = "🔄 New Game"
    override val restartDialogDesc = "Are you sure you want to start a new game? Current progress will be reset."
    override val restartDialogConfirm = "YES, RESTART"
    override val pauseDialogTitle = "⏸ GAME PAUSED"
    override val victoryTitle = "CONGRATULATIONS!"
    override val victoryDesc = "\\"You built Romania, tile by tile!\\""
    override val btnContinuePlaying = "▶ CONTINUE"
    override val btnPlayAgain = "🔄 PLAY AGAIN"
    override val btnHome = "🏠 MAIN MENU"
    override val gameOverTitle = "GAME OVER"
    override val gameOverDesc = "No more moves available."
    override val gameOverNewRecord = "🏆 NEW RECORD! "
    override fun gameOverScore(score: Int, highScore: Int) = "Final score: $score\\nRecord: $highScore"
    override val continueGameBtn = "▶ CONTINUE GAME"
    override val continueAdBtn = "🎬 CONTINUE (AD)"
    override val extraUndoTitle = "↩ Extra Undo"
    override val extraUndoBtnFree = "▶ GET UNDO"
    override val extraUndoBtnAd = "🎬 WATCH AD (+1 UNDO)"
    override val extraUndoDescAd = "Use a chance to undo your last move by watching a short ad."
    override val extraUndoDescFree = "Use a chance to undo your last move for free."
    override val levelCompleteTitle = "LEVEL COMPLETE!"
    override val rewardUnlocked = "🎁 Reward unlocked:"
    override val resetProgressTitle = "⚠️ Reset Progress"
    override val resetProgressDesc = "Are you absolutely sure you want to delete ALL progress, levels, and achievements? This action cannot be undone!"
    override val resetProgressConfirm = "YES, RESET ALL"

    override fun getLevelName(level: Int) = "LEVEL $level"
    override val infiniteModeTop = "♾️ INFINITE MODE"
    override val score = "SCORE"
    override val recordUpper = "RECORD"
    override val restartBtn = "RESTART"
    override val undoBtn = "UNDO"
    override fun objectiveAdventure(level: Int, emoji: String, name: String, val_: Int) = "🎯 OBJECTIVE LEVEL $level: Discover $emoji $name ($val_)"
    override val objectiveInfinite = "🎯 OBJECTIVE: Reach the 2048 tile!"
    override fun objectiveAdventureDesc(name: String) = "\\"Merge two identical tiles to discover $name!\\""
    override val objectiveInfiniteDesc = "\\"Merge two identical tiles to build Romania, tile by tile!\\""
    override val gamePaused = "GAME PAUSED"
    override val resumeGameBtn = "RESUME GAME"

    override val fallbackName = "Mystery "
    override val fallbackDesc = "An unknown tile, appearing from nowhere."
    override val fallbackBadge = "???"

    override val gameLevel1Name = "The Beginning"
    override val gameLevel1Reward = "Pretzel (8)"
    override val gameLevel2Name = "The Snack"
    override val gameLevel2Reward = "Pie (16)"
    override val gameLevel3Name = "First Course"
    override val gameLevel3Reward = "Tripe Soup (32)"
    override val gameLevel4Name = "At the Sheepfold"
    override val gameLevel4Reward = "Polenta & Cheese (64)"
    override val gameLevel5Name = "The Barbecue"
    override val gameLevel5Reward = "Mici (128)"
    override val gameLevel6Name = "Sunday Dinner"
    override val gameLevel6Reward = "Sarmale (256)"
    override val gameLevel7Name = "The Tradition"
    override val gameLevel7Reward = "Cozonac (512)"
    override val gameLevel8Name = "The Heritage"
    override val gameLevel8Reward = "Bran Castle (1024)"
    override val gameLevel9Name = "The Symbol"
    override val gameLevel9Reward = "Romanian Athenaeum (2048)"
    override val gameLevel10Name = "The Heroes"
    override val gameLevel10Reward = "Michael the Brave (4096)"
    override val gameLevel11Name = "The Legend"
    override val gameLevel11Reward = "Dacian Wolf (8192)"
    override val gameLevel12Name = "The Absolute"
    override val gameLevel12Reward = "Royal Crown (16384)"

    override val reg2name = "Pretzel"
    override val reg2desc = "The Pretzel – the official fuel of the Romanian in a hurry."
    override val reg2badge = "Snack"
    override val reg4name = "Pie"
    override val reg4desc = "Whether with cheese, apples, or pumpkin, it's always warm and good."
    override val reg4badge = "Dessert"
    override val reg8name = "Tripe Soup"
    override val reg8desc = "The ultimate remedy for any heavy morning."
    override val reg8badge = "1st Course"
    override val reg16name = "Polenta with Cheese"
    override val reg16desc = "Simple, authentic, irreplaceable at the sheepfold."
    override val reg16badge = "Tradition"
    override val reg32name = "Mici with Mustard"
    override val reg32desc = "The uncrowned kings of any May 1st barbecue."
    override val reg32badge = "Barbecue"
    override val reg64name = "Sarmale"
    override val reg64desc = "Made with love by grandma. Always better the next day."
    override val reg64badge = "Feast"
    override val reg128name = "Cozonac"
    override val reg128desc = "The aroma of Christmas and Easter in every home."
    override val reg128badge = "Holiday"
    override val reg256name = "Ibrik Coffee"
    override val reg256desc = "How mornings started before espresso machines."
    override val reg256badge = "Energy"
    override val reg512name = "Bran Castle"
    override val reg512desc = "Dracula's legend, visited by the whole world."
    override val reg512badge = "Monument"
    override val reg1024name = "Romanian Athenaeum"
    override val reg1024desc = "The symbol of culture and elegance in the heart of Bucharest."
    override val reg1024badge = "Culture"
    override val reg2048name = "Romania 2048"
    override val reg2048desc = "You reached the ultimate goal of the game! Congratulations!"
    override val reg2048badge = "Victory"
    override val reg4096name = "Michael the Brave"
    override val reg4096desc = "Symbol of courage and the union of all Romanians."
    override val reg4096badge = "History"
    override val reg8192name = "Dacian Wolf"
    override val reg8192desc = "The standard of our ancestors, striking fear into enemies."
    override val reg8192badge = "Mythology"
    override val reg16384name = "Royal Crown"
    override val reg16384desc = "The Steel Crown, forged from the cannons at Plevna."
    override val reg16384badge = "Royalty"

    override fun getAchievementTitle(id: String) = when(id) {
        "1" -> "First Snack"
        "2" -> "Something Sweet"
        "3" -> "Soup Time"
        "4" -> "Authentic Romanian"
        "5" -> "Grill Master"
        "6" -> "Family Dinner"
        "7" -> "Holiday Scent"
        "8" -> "Coffee Break"
        "9" -> "Tourist in Transylvania"
        "10" -> "Man of Culture"
        "11" -> "True Patriot"
        "12" -> "National Hero"
        "13" -> "Dacian Spirit"
        "14" -> "Blue Blood"
        "15" -> "Consistent Player"
        "16" -> "2048 Master"
        "17" -> "Beginner"
        "18" -> "Amateur"
        "19" -> "Professional"
        "20" -> "Traveler"
        else -> "Unknown"
    }
    
    override fun getAchievementDesc(id: String) = when(id) {
        "1" -> "Discover tile 4 (Pie)"
        "2" -> "Discover tile 8 (Soup)"
        "3" -> "Discover tile 16 (Polenta)"
        "4" -> "Discover tile 32 (Mici)"
        "5" -> "Discover tile 64 (Sarmale)"
        "6" -> "Discover tile 128 (Cozonac)"
        "7" -> "Discover tile 256 (Coffee)"
        "8" -> "Discover tile 512 (Castle)"
        "9" -> "Discover tile 1024 (Athenaeum)"
        "10" -> "Discover tile 2048 (Romania)"
        "11" -> "Discover tile 4096 (Michael the Brave)"
        "12" -> "Discover tile 8192 (Dacian Wolf)"
        "13" -> "Discover tile 16384 (Royal Crown)"
        "14" -> "Get the rarest possible tile!"
        "15" -> "Complete 3 levels in Adventure Mode"
        "16" -> "Complete 10 levels in Adventure Mode"
        "17" -> "Reach a score of 10,000 pts"
        "18" -> "Reach a score of 25,000 pts"
        "19" -> "Reach a score of 50,000 pts"
        "20" -> "Play 5 games in Infinite Mode"
        else -> "Unknown"
    }
}
""")
