package com.example.ui.strings

object StringsEn : AppStrings {
    override val dpadUp = "Up"
    override val dpadDown = "Down"
    override val dpadLeft = "Left"
    override val dpadRight = "Right"
    override val appTitle = "ROMANIA 2048"
    override val appSubtitle = "Build Romania, tile by tile!"
    override val playNow = "PLAY NOW"
    override val record = "Record"
    override val currentLevelTitle = "CURRENT LEVEL"
    override val levelPrefix = "Level "
    override val collectionTitle = "COLLECTION"
    override val btnLevels = "LEVELS"
    override val btnAchievements = "ACHIEVEMENTS"
    override val btnSettings = "SETTINGS"
    override val btnAbout = "ABOUT"
    override val removeAdsTitle = "Play Ad-Free"
    override val adsRemovedMsg = "Interstitial ads are disabled"
    override val removeAdsDesc = "Remove interstitial ads and enjoy a smoother gaming experience."
    override val removeAdsBtn = "REMOVE ADS — 6.99 RON"
    override val removeAdsDisclaimer = "One-time purchase. Rewarded ads for Undo and Continue after Game Over will still be available."
    override val restorePurchaseBtn = "RESTORE PURCHASE"
    override val languageSelector = "🌐 Language: EN"

    override val modeSelectionTitle = "🎮 CHOOSE GAME MODE"
    override val modeSelectionDesc = "Select the gaming experience you want:"
    override val modeAdventureTitle = "ADVENTURE MODE"
    override val modeAdventureDesc = "Level-based progression"
    override val modeAdventureLongDesc = "Discover Romanian foods, complete your collection and unlock new levels step by step."
    override val unlockedLevelsPrefix = "Unlocked levels: "
    override val viewLevelsBtn = "VIEW LEVELS"
    override val modeInfiniteTitle = "INFINITE MODE"
    override val modeInfiniteDesc = "Endless classic"
    override val modeInfiniteLongDesc = "Play without limits, merge as many tiles as you can and try to beat your personal high score."

    override val levelsTitle = "🗺 LEVELS"
    override val levelsSubtitle = "Progress through Romania's levels by merging tiles and reaching the set objectives!"
    override val levelObjectivePrefix = "Objective: Discover Tile "
    override val levelRewardPrefix = "Reward: "
    override val levelBtnPlay = "PLAY"
    override val levelBtnReplay = "REPLAY"

    override val collectionHeaderTitle = "🎨 COLLECTION"
    override val collectionSubtitle = "All the Romanian tiles you have created in the game "
    override val statusUnlocked = "UNLOCKED"
    override val statusLocked = "LOCKED"
    override val contentDescBack = "Back"
    override val billingNotConnected = "Google Play Billing is not connected yet."
    override val billingProductNotFound = "Product 'remove_ads' not found in Google Play Console."
    override val billingAdsAlreadyRemoved = "Ads are already removed!"
    override fun billingError(msg: String) = "Purchase error: $msg"
    override val billingSuccess = "Thank you! Ads have been permanently removed."
    override val pointsSuffix = " pts"
    override val contentDescPlay = "Play"
    override val contentDescPurchased = "Purchased"
    override val contentDescLocked = "Locked"
    override val contentDescUnlocked = "Unlocked"
    override val contentDescQuickMenu = "Quick Menu"
    override val contentDescPause = "Pause"
    override val unknownTile = "???"
    override fun undoFreeRemaining(remaining: Int, total: Int) = "UNDO ($remaining/$total)"
    override val undoAdTooltipPurchased = "UNDO (+1)"
    override val undoAdTooltipAd = "UNDO 🎬"
    override fun collectionLockedDesc(value: Int) = "Reach tile $value in the game to unlock this traditional item!"

    override val achievementsTitle = "🏆 ACHIEVEMENTS"
    override fun achievementsSubtitle(count: Int) = "Unlock all $count achievements "

    override val aboutTitle = "ℹ ABOUT THE GAME"
    override val aboutDescription = "\"ROMANIA 2048 is a casual game inspired by Romania, the big and small things that define us, and the joy of building something step by step.\""
    override val version = "Version 1.0.0"
    override val copyright = "© Romania 2048"

    override val settingsTitle = "⚙ SETTINGS"
    override val audioSection = "AUDIO & VIBRATION"
    override val visualSection = "🌙 VISUAL THEME"
    override val gamePrefsSection = "⚡ GAME PREFERENCES"
    override val resetSection = "🗑️ RESET PROGRESS"
    override val musicVol = "🎵 MUSIC VOLUME: "
    override val sfxVol = "🔊 SFX VOLUME: "
    override val vibration = "🔔 VIBRATION"
    override val themeLight = "LIGHT"
    override val themeDark = "DARK"
    override val themeSystem = "SYSTEM"
    override val romanianTheme = "🎨 ROMANIAN THEME"
    override val animations = "⚡ ANIMATIONS"
    override val confirmRestartPref = "CONFIRM RESTART"

    override val achievementUnlocked = "🏆 ACHIEVEMENT UNLOCKED!"

    override val btnCancel = "CANCEL"
    override val restartDialogTitle = "🔄 New Game"
    override val restartDialogDesc = "Are you sure you want to start a new game? Current progress will be reset."
    override val restartDialogConfirm = "YES, RESTART"
    override val pauseDialogTitle = "⏸ GAME PAUSED"
    override val victoryTitle = "CONGRATULATIONS!"
    override val victoryDesc = "\"You built Romania, tile by tile!\""
    override val btnContinuePlaying = "▶ CONTINUE"
    override val btnPlayAgain = "🔄 PLAY AGAIN"
    override val btnHome = "🏠 MAIN MENU"
    override val gameOverTitle = "GAME OVER"
    override val gameOverDesc = "No more moves available."
    override val gameOverNewRecord = "🏆 NEW RECORD! "
    override fun gameOverScore(score: Int, highScore: Int) = "Final score: $score\nRecord: $highScore"
    override val continueGameBtn = "▶ CONTINUE GAME"
    override val continueAdBtn = "🎬 CONTINUE (AD)"
    override val extraUndoTitle = "↩ Extra Undo"
    override val extraUndoBtnFree = "▶ GET UNDO"
    override val extraUndoBtnAd = "🎬 WATCH AD (+1 UNDO)"
    override val extraUndoDescAd = "Use a chance to undo your last move by watching a short ad."
    override val extraUndoDescFree = "Use a chance to undo your last move for free."
    override val levelCompleteTitle = "LEVEL COMPLETE!"
    override val rewardUnlocked = "🎁 Reward unlocked:"
    override val resetProgressTitle = "⚠️ Reset Progress"
    override val resetProgressDesc = "Are you absolutely sure you want to delete ALL progress, levels, and achievements? This action cannot be undone!"
    override val resetProgressConfirm = "YES, RESET ALL"

    override fun getLevelName(level: Int) = "LEVEL $level"
    override val infiniteModeTop = "♾️ INFINITE MODE"
    override val score = "SCORE"
    override val recordUpper = "RECORD"
    override val restartBtn = "RESTART"
    override val undoBtn = "UNDO"
    override fun objectiveAdventure(level: Int, emoji: String, name: String, val_: Int) = "🎯 OBJECTIVE LEVEL $level: Discover $emoji $name ($val_)"
    override val objectiveInfinite = "🎯 OBJECTIVE: Reach the 2048 tile!"
    override fun objectiveAdventureDesc(name: String) = "\"Merge two identical tiles to discover $name!\""
    override val objectiveInfiniteDesc = "\"Merge two identical tiles to build Romania, tile by tile!\""
    override val gamePaused = "GAME PAUSED"
    override val resumeGameBtn = "RESUME GAME"

    override val fallbackName = "Mystery "
    override val fallbackDesc = "An unknown tile, appearing from nowhere."
    override val fallbackBadge = "???"

    override val gameLevel1Name = "The Beginning"
    override val gameLevel1Reward: String get() = "$reg8name (8)"
    override val gameLevel2Name = "The Snack"
    override val gameLevel2Reward: String get() = "$reg16name (16)"
    override val gameLevel3Name = "First Course"
    override val gameLevel3Reward: String get() = "$reg32name (32)"
    override val gameLevel4Name = "At the Sheepfold"
    override val gameLevel4Reward: String get() = "$reg64name (64)"
    override val gameLevel5Name = "The Barbecue"
    override val gameLevel5Reward: String get() = "$reg128name (128)"
    override val gameLevel6Name = "Sunday Dinner"
    override val gameLevel6Reward: String get() = "$reg256name (256)"
    override val gameLevel7Name = "The Tradition"
    override val gameLevel7Reward: String get() = "$reg512name (512)"
    override val gameLevel8Name = "The Heritage"
    override val gameLevel8Reward: String get() = "$reg1024name (1024)"
    override val gameLevel9Name = "The Symbol"
    override val gameLevel9Reward: String get() = "$reg2048name (2048)"
    override val gameLevel10Name = "The Heroes"
    override val gameLevel10Reward: String get() = "$reg4096name (4096)"
    override val gameLevel11Name = "The Legend"
    override val gameLevel11Reward: String get() = "$reg8192name (8192)"
    override val gameLevel12Name = "The Absolute"
    override val gameLevel12Reward: String get() = "$reg16384name (16384)"

    override val reg2name = "Pretzel"
    override val reg2desc = "The Pretzel – the official fuel of the Romanian in a hurry."
    override val reg2badge = "Snack"
    override val reg4name = "Pie"
    override val reg4desc = "Whether with cheese, apples, or pumpkin, it's always warm and good."
    override val reg4badge = "Dessert"
    override val reg8name = "Tripe Soup"
    override val reg8desc = "The ultimate remedy for any heavy morning."
    override val reg8badge = "1st Course"
    override val reg16name = "Cheese"
    override val reg16desc = "Simple, authentic, irreplaceable at the sheepfold."
    override val reg16badge = "Tradition"
    override val reg32name = "Chicken Drumsticks"
    override val reg32desc = "The uncrowned kings of any May 1st barbecue."
    override val reg32badge = "Barbecue"
    override val reg64name = "Cabbage Rolls"
    override val reg64desc = "Made with love by grandma. Always better the next day."
    override val reg64badge = "Feast"
    override val reg128name = "Stew"
    override val reg128desc = "The aroma of Christmas and Easter in every home."
    override val reg128badge = "Holiday"
    override val reg256name = "Ibrik Coffee"
    override val reg256desc = "How mornings started before espresso machines."
    override val reg256badge = "Energy"
    override val reg512name = "Bran Castle"
    override val reg512desc = "Dracula's legend, visited by the whole world."
    override val reg512badge = "Monument"
    override val reg1024name = "Romanian Athenaeum"
    override val reg1024desc = "The symbol of culture and elegance in the heart of Bucharest."
    override val reg1024badge = "Culture"
    override val reg2048name = "Romania 2048"
    override val reg2048desc = "You reached the ultimate goal of the game! Congratulations!"
    override val reg2048badge = "Victory"
    override val reg4096name = "Michael the Brave"
    override val reg4096desc = "Symbol of courage and the union of all Romanians."
    override val reg4096badge = "History"
    override val reg8192name = "Eagle"
    override val reg8192desc = "The standard of our ancestors, striking fear into enemies."
    override val reg8192badge = "Mythology"
    override val reg16384name = "Royal Crown"
    override val reg16384desc = "The Steel Crown, forged from the cannons at Plevna."
    override val reg16384badge = "Royalty"

    override fun getAchievementTitle(id: String) = when(id) {
        "1" -> "First Snack"
        "2" -> "Something Sweet"
        "3" -> "Soup Time"
        "4" -> "Authentic Romanian"
        "5" -> "Grill Master"
        "6" -> "Family Dinner"
        "7" -> "Holiday Scent"
        "8" -> "Coffee Break"
        "9" -> "Tourist in Transylvania"
        "10" -> "Man of Culture"
        "11" -> "True Patriot"
        "12" -> "National Hero"
        "13" -> "Dacian Spirit"
        "14" -> "Beyond the Limit"
        "15" -> "Second Chances"
        "16" -> "Warming Up"
        "17" -> "Beginner"
        "18" -> "Amateur"
        "19" -> "Professional"
        "20" -> "Traveler"
        "21" -> "Avid Collector"
        "22" -> "Supreme Speed"
        "23" -> "Prosperous Restart"
        "24" -> "White Nights"
        "25" -> "Romanian Heart"
        else -> "Unknown"
    }
    
    override fun getAchievementDesc(id: String) = when(id) {
        "1" -> "Discover tile 2 ($reg2name)"
        "2" -> "Discover tile 4 ($reg4name)"
        "3" -> "Discover tile 8 ($reg8name)"
        "4" -> "Discover tile 16 ($reg16name)"
        "5" -> "Discover tile 32 ($reg32name)"
        "6" -> "Discover tile 64 ($reg64name)"
        "7" -> "Discover tile 128 ($reg128name)"
        "8" -> "Discover tile 256 ($reg256name)"
        "9" -> "Discover tile 512 ($reg512name)"
        "10" -> "Discover tile 1024 ($reg1024name)"
        "11" -> "Discover tile 2048 ($reg2048name)"
        "12" -> "Discover tile 4096 ($reg4096name)"
        "13" -> "Discover tile 8192 ($reg8192name)"
        "14" -> "Keep playing after reaching 2048!"
        "15" -> "Use the Undo feature 3 times."
        "16" -> "Make your first 10 moves."
        "17" -> "Reach a score of 10,000 pts."
        "18" -> "Reach a score of 25,000 pts."
        "19" -> "Reach a score of 50,000 pts."
        "20" -> "Unlock 5 levels in Adventure Mode."
        "21" -> "Unlock 8 tiles in the Collection."
        "22" -> "Make 50 moves in a single game."
        "23" -> "Start a new game after scoring over 100."
        "24" -> "Switch the app to Dark mode."
        "25" -> "Unlock 7 levels in Adventure Mode."
        else -> "Unknown"
    }
}
