package com.example.ui.strings

object StringsRo : AppStrings {
    override val dpadUp = "Sus"
    override val dpadDown = "Jos"
    override val dpadLeft = "Stânga"
    override val dpadRight = "Dreapta"
    override val appTitle = "ROMÂNIA 2048"
    override val appSubtitle = "Construiește România, piesă cu piesă!"
    override val playNow = "JOACĂ ACUM"
    override val record = "Record"
    override val currentLevelTitle = "NIVEL ACTUAL"
    override val levelPrefix = "Nivel "
    override val collectionTitle = "COLECȚIE"
    override val btnLevels = "NIVELURI"
    override val btnAchievements = "REALIZĂRI"
    override val btnSettings = "SETĂRI"
    override val btnAbout = "DESPRE JOC"
    override val removeAdsTitle = "Joacă fără reclame"
    override val adsRemovedMsg = "Reclamele interstițiale sunt dezactivate"
    override val removeAdsDesc = "Elimină reclamele interstițiale și bucură-te de o experiență de joc mai plăcută."
    override val removeAdsBtn = "ELIMINĂ RECLAMELE — 6,99 lei"
    override val removeAdsDisclaimer = "Achiziție unică. Reclamele recompensate pentru Undo și Continuă după Game Over rămân disponibile."
    override val restorePurchaseBtn = "RESTAUREAZĂ ACHIZIȚIA"
    override val languageSelector = "🌐 Limba: RO"

    override val modeSelectionTitle = "🎮 ALEGE MODUL DE JOC"
    override val modeSelectionDesc = "Selectează experiența de joc pe care o dorești:"
    override val modeAdventureTitle = "MOD AVENTURĂ"
    override val modeAdventureDesc = "Progres pe niveluri"
    override val modeAdventureLongDesc = "Descoperă preparatele românești, completează colecția și deblochează noi niveluri pas cu pas."
    override val unlockedLevelsPrefix = "Niveluri deblocate: "
    override val viewLevelsBtn = "VEZI NIVELURILE"
    override val modeInfiniteTitle = "MOD INFINIT"
    override val modeInfiniteDesc = "Clasic fără sfârșit"
    override val modeInfiniteLongDesc = "Joacă fără limită, combină cât mai multe piese și încearcă să-ți depășești recordul personal."

    override val levelsTitle = "🗺 NIVELURI"
    override val levelsSubtitle = "Progresează prin nivelurile României combinând piese și atingând obiectivele stabilite!"
    override val levelObjectivePrefix = "Obiectiv: Descoperă Piesa "
    override val levelRewardPrefix = "Recompensă: "
    override val levelBtnPlay = "JOACĂ"
    override val levelBtnReplay = "REJOACĂ"

    override val collectionHeaderTitle = "🎨 COLECȚIE"
    override val collectionSubtitle = "Toate piesele românești pe care le-ai creat în joc "
    override val statusUnlocked = "DEBLOCAT"
    override val statusLocked = "BLOCAT"
    override val contentDescBack = "Înapoi"
    override val billingNotConnected = "Google Play Billing nu este conectat încă."
    override val billingProductNotFound = "Produsul 'remove_ads' nu a fost găsit în Google Play Console."
    override val billingAdsAlreadyRemoved = "Reclamele sunt deja eliminate!"
    override fun billingError(msg: String) = "Eroare achiziție: $msg"
    override val billingSuccess = "Mulțumim! Reclamele au fost eliminate permanent."
    override val billingRestoredSuccess = "Achiziția a fost restaurată."
    override val billingNoPurchaseFound = "Nu a fost găsită nicio achiziție de restaurat."
    override val adNotReady = "Reclama nu este disponibilă încă. Încearcă din nou."
    override val pointsSuffix = " puncte"
    override val contentDescPlay = "Joacă"
    override val contentDescPurchased = "Achiziționat"
    override val contentDescLocked = "Blocat"
    override val contentDescUnlocked = "Deblocat"
    override val contentDescQuickMenu = "Meniu Rapid"
    override val contentDescPause = "Pauză"
    override val unknownTile = "???"
    override fun undoFreeRemaining(remaining: Int, total: Int) = "UNDO ($remaining/$total)"
    override val undoAdTooltipPurchased = "UNDO (+1)"
    override val undoAdTooltipAd = "UNDO 🎬"
    override fun collectionLockedDesc(value: Int) = "Atinge piesa $value în joc pentru a debloca acest obiect tradițional!"

    override val achievementsTitle = "🏆 REALIZĂRI"
    override fun achievementsSubtitle(count: Int) = "Deblochează toate cele $count de realizări "

    override val aboutTitle = "ℹ DESPRE JOC"
    override val aboutDescription = "„ROMÂNIA 2048 este un joc casual inspirat de România, de lucrurile mici și mari care ne definesc și de plăcerea de a construi ceva pas cu pas.”"
    override val version = "Versiunea 1.0.0"
    override val copyright = "© România 2048"

    override val settingsTitle = "⚙ SETĂRI"
    override val audioSection = "AUDIO & VIBRAȚII"
    override val visualSection = "🌙 TEMĂ VIZUALĂ"
    override val gamePrefsSection = "⚡ PREFERINȚE JOC"
    override val resetSection = "🗑️ RESETARE PROGRES"
    override val musicVol = "🎵 VOLUM MUZICĂ: "
    override val sfxVol = "🔊 VOLUM EFECTE SONORE: "
    override val vibration = "🔔 VIBRAȚII"
    override val themeLight = "LIGHT"
    override val themeDark = "DARK"
    override val themeSystem = "SYSTEM"
    override val romanianTheme = "🎨 TEMĂ ROMÂNEASCĂ"
    override val animations = "⚡ ANIMAȚII"
    override val confirmRestartPref = "CONFIRMĂ RESTART"

    override val achievementUnlocked = "🏆 REALIZARE DEBLOCATĂ!"

    override val btnCancel = "ANULEAZĂ"
    override val restartDialogTitle = "🔄 Joc Nou"
    override val restartDialogDesc = "Ești sigur că vrei să începi un joc nou? Progresul jocului curent va fi resetat."
    override val restartDialogConfirm = "DA, RESTART"
    override val pauseDialogTitle = "⏸ JOC PUS PE PAUZĂ"
    override val victoryTitle = "FELICITĂRI!"
    override val victoryDesc = "„Ai construit România, piesă cu piesă!”"
    override val btnContinuePlaying = "▶ CONTINUĂ"
    override val btnPlayAgain = "🔄 JOACĂ DIN NOU"
    override val btnHome = "🏠 MENIU PRINCIPAL"
    override val gameOverTitle = "GAME OVER"
    override val gameOverDesc = "Nu mai ai mutări disponibile."
    override val gameOverNewRecord = "🏆 RECORD NOU! "
    override fun gameOverScore(score: Int, highScore: Int) = "Scor final: $score\nRecord: $highScore"
    override val continueGameBtn = "▶ CONTINUĂ JOCUL"
    override val continueAdBtn = "🎬 CONTINUĂ (RECLAMĂ)"
    override val extraUndoTitle = "↩ Undo Suplimentar"
    override val extraUndoBtnFree = "▶ PRIMEȘTE UNDO"
    override val extraUndoBtnAd = "🎬 VEZI RECLAMĂ (+1 UNDO)"
    override val extraUndoDescAd = "Folosește o șansă pentru a-ți corecta ultima mutare urmărind o scurtă reclamă."
    override val extraUndoDescFree = "Folosește o șansă pentru a-ți corecta ultima mutare gratuit."
    override val levelCompleteTitle = "NIVEL COMPLETAT!"
    override val rewardUnlocked = "🎁 Recompensă deblocată:"
    override val resetProgressTitle = "⚠️ Resetare Progres"
    override val resetProgressDesc = "Ești absolut sigur că vrei să ștergi TOT progresul, nivelurile și realizările? Această acțiune nu poate fi anulată!"
    override val resetProgressConfirm = "DA, RESETEAZĂ TOT"

    override fun getLevelName(level: Int) = "NIVEL $level"
    override val infiniteModeTop = "♾️ MOD INFINIT"
    override val score = "SCOR"
    override val recordUpper = "RECORD"
    override val restartBtn = "RESTART"
    override val undoBtn = "UNDO"
    override fun objectiveAdventure(level: Int, emoji: String, name: String, val_: Int) = "🎯 OBIECTIV NIVEL $level: Descoperă $emoji $name ($val_)"
    override val objectiveInfinite = "🎯 OBIECTIV: Ajunge la piesa 2048!"
    override fun objectiveAdventureDesc(name: String) = "„Combină două piese identice pentru a descoperi $name!”"
    override val objectiveInfiniteDesc = "„Combină două piese identice pentru a construi România, piesă cu piesă!”"
    override val gamePaused = "JOC ÎN PAUZĂ"
    override val resumeGameBtn = "CONTINUĂ JOCUL"

    override val fallbackName = "Mister "
    override val fallbackDesc = "O piesă necunoscută, apărută din neant."
    override val fallbackBadge = "???"

    override val gameLevel1Name = "Începutul"
    override val gameLevel1Reward: String get() = "$reg8name (8)"
    override val gameLevel2Name = "Gustarea"
    override val gameLevel2Reward: String get() = "$reg16name (16)"
    override val gameLevel3Name = "Felul Întâi"
    override val gameLevel3Reward: String get() = "$reg32name (32)"
    override val gameLevel4Name = "La Stână"
    override val gameLevel4Reward: String get() = "$reg64name (64)"
    override val gameLevel5Name = "Grătarul"
    override val gameLevel5Reward: String get() = "$reg128name (128)"
    override val gameLevel6Name = "Masa de Duminică"
    override val gameLevel6Reward: String get() = "$reg256name (256)"
    override val gameLevel7Name = "Tradiția"
    override val gameLevel7Reward: String get() = "$reg512name (512)"
    override val gameLevel8Name = "Moștenirea"
    override val gameLevel8Reward: String get() = "$reg1024name (1024)"
    override val gameLevel9Name = "Simbolul"
    override val gameLevel9Reward: String get() = "$reg2048name (2048)"
    override val gameLevel10Name = "Eroii"
    override val gameLevel10Reward: String get() = "$reg4096name (4096)"
    override val gameLevel11Name = "Legenda"
    override val gameLevel11Reward: String get() = "$reg8192name (8192)"
    override val gameLevel12Name = "Absolutul"
    override val gameLevel12Reward: String get() = "$reg16384name (16384)"

    override val reg2name = "Covrig"
    override val reg2desc = "Covrigul – combustibilul oficial al românului grăbit."
    override val reg2badge = "Gustare"
    override val reg4name = "Plăcintă"
    override val reg4desc = "Fie că e cu brânză, mere sau dovleac, e mereu caldă și bună."
    override val reg4badge = "Desert"
    override val reg8name = "Ciorbă"
    override val reg8desc = "Remediul suprem pentru orice dimineață grea."
    override val reg8badge = "Felul 1"
    override val reg16name = "Brânză"
    override val reg16desc = "Simplă, autentică, de neînlocuit la stână."
    override val reg16badge = "Tradiție"
    override val reg32name = "Copane"
    override val reg32desc = "Regii neîncoronați ai oricărui grătar de 1 Mai."
    override val reg32badge = "Grătar"
    override val reg64name = "Sarmale"
    override val reg64desc = "Făcute cu drag de bunica. Mereu mai bune a doua zi."
    override val reg64badge = "Festin"
    override val reg128name = "Tocăniță"
    override val reg128desc = "Aroma Crăciunului și a Paștelui în fiecare casă."
    override val reg128badge = "Sărbătoare"
    override val reg256name = "Cafea la Ibric"
    override val reg256desc = "Cum se începeau diminețile înainte de espressoare."
    override val reg256badge = "Energie"
    override val reg512name = "Castelul Bran"
    override val reg512desc = "Legenda lui Dracula, vizitată de o lume întreagă."
    override val reg512badge = "Monument"
    override val reg1024name = "Ateneul Român"
    override val reg1024desc = "Simbolul culturii și eleganței din inima Bucureștiului."
    override val reg1024badge = "Cultură"
    override val reg2048name = "România 2048"
    override val reg2048desc = "Ai atins scopul suprem al jocului! Felicitări!"
    override val reg2048badge = "Victorie"
    override val reg4096name = "Mihai Viteazul"
    override val reg4096desc = "Simbol al curajului și al unirii tuturor românilor."
    override val reg4096badge = "Istorie"
    override val reg8192name = "Vultur"
    override val reg8192desc = "Stindardul strămoșilor noștri, stârnind frica în inamici."
    override val reg8192badge = "Mitologie"
    override val reg16384name = "Coroana Regală"
    override val reg16384desc = "Coroana de oțel, forjată din tunurile de la Plevna."
    override val reg16384badge = "Regalitate"

    override fun getAchievementTitle(id: String) = when(id) {
        "1" -> "Prima Gustare"
        "2" -> "Ceva Dulce"
        "3" -> "La Ciorbă"
        "4" -> "Autentic Românesc"
        "5" -> "Grătaragiu"
        "6" -> "Masa în Familie"
        "7" -> "Miros de Sărbătoare"
        "8" -> "Pauza de Cafea"
        "9" -> "Turist în Transilvania"
        "10" -> "Om de Cultură"
        "11" -> "Patriot Adevărat"
        "12" -> "Erou Național"
        "13" -> "Spirit Dacic"
        "14" -> "Dincolo de Limite"
        "15" -> "A Doua Șansă"
        "16" -> "Încălzirea"
        "17" -> "Începător"
        "18" -> "Amator"
        "19" -> "Profesionist"
        "20" -> "Călător"
        "21" -> "Colecționar Harnic"
        "22" -> "Viteză Supremă"
        "23" -> "Reînceput Prosper"
        "24" -> "Nopți Albe"
        "25" -> "Inimă de Român"
        else -> "Necunoscut"
    }
    
    override fun getAchievementDesc(id: String) = when(id) {
        "1" -> "Descoperă piesa 2 ($reg2name)"
        "2" -> "Descoperă piesa 4 ($reg4name)"
        "3" -> "Descoperă piesa 8 ($reg8name)"
        "4" -> "Descoperă piesa 16 ($reg16name)"
        "5" -> "Descoperă piesa 32 ($reg32name)"
        "6" -> "Descoperă piesa 64 ($reg64name)"
        "7" -> "Descoperă piesa 128 ($reg128name)"
        "8" -> "Descoperă piesa 256 ($reg256name)"
        "9" -> "Descoperă piesa 512 ($reg512name)"
        "10" -> "Descoperă piesa 1024 ($reg1024name)"
        "11" -> "Descoperă piesa 2048 ($reg2048name)"
        "12" -> "Descoperă piesa 4096 ($reg4096name)"
        "13" -> "Descoperă piesa 8192 ($reg8192name)"
        "14" -> "Continuă jocul după ce ai atins 2048!"
        "15" -> "Folosește funcția Undo de 3 ori."
        "16" -> "Efectuează primele 10 mutări."
        "17" -> "Atinge un scor de 10.000 pct."
        "18" -> "Atinge un scor de 25.000 pct."
        "19" -> "Atinge un scor de 50.000 pct."
        "20" -> "Deblochează 5 niveluri în Modul Aventură."
        "21" -> "Deblochează 8 piese în Colecție."
        "22" -> "Efectuează 50 de mutări într-un joc."
        "23" -> "Începe un joc nou după ce ai depășit 100 pct."
        "24" -> "Comută aplicația în modul Dark."
        "25" -> "Deblochează 7 niveluri în Modul Aventură."
        else -> "Necunoscut"
    }
}
